apiVersion: operator.openshift.io/v1
kind: ServiceCA
metadata:
  name: cluster
  annotations:
    release.openshift.io/create-only: "true"
spec:
  managementState: Managed
  # Configure the log level of managed deployments
  logLevel: "4"
