apiVersion: servicecertsigner.config.openshift.io/v1alpha1
kind: CABundleInjectorConfig
caBundleFile: /var/run/configmaps/signing-cabundle/ca-bundle.crt
authentication:
  disabled: true
authorization:
  disabled: true
