// Code generated by go-bindata.
// sources:
// bindata/v4.0.0/apiservice-cabundle-controller/defaultconfig.yaml
// bindata/v4.0.0/cabundle-injection-controller/clusterrole.yaml
// bindata/v4.0.0/cabundle-injection-controller/clusterrolebinding.yaml
// bindata/v4.0.0/cabundle-injection-controller/cm.yaml
// bindata/v4.0.0/cabundle-injection-controller/defaultconfig.yaml
// bindata/v4.0.0/cabundle-injection-controller/deployment.yaml
// bindata/v4.0.0/cabundle-injection-controller/ns.yaml
// bindata/v4.0.0/cabundle-injection-controller/role.yaml
// bindata/v4.0.0/cabundle-injection-controller/rolebinding.yaml
// bindata/v4.0.0/cabundle-injection-controller/sa.yaml
// bindata/v4.0.0/cabundle-injection-controller/signing-cabundle.yaml
// bindata/v4.0.0/service-serving-cert-signer-controller/clusterrole.yaml
// bindata/v4.0.0/service-serving-cert-signer-controller/clusterrolebinding.yaml
// bindata/v4.0.0/service-serving-cert-signer-controller/cm.yaml
// bindata/v4.0.0/service-serving-cert-signer-controller/defaultconfig.yaml
// bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
// bindata/v4.0.0/service-serving-cert-signer-controller/ns.yaml
// bindata/v4.0.0/service-serving-cert-signer-controller/role.yaml
// bindata/v4.0.0/service-serving-cert-signer-controller/rolebinding.yaml
// bindata/v4.0.0/service-serving-cert-signer-controller/sa.yaml
// bindata/v4.0.0/service-serving-cert-signer-controller/signing-secret.yaml
// DO NOT EDIT!

package v4_00_assets

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _v400ApiserviceCabundleControllerDefaultconfigYaml = []byte(`apiVersion: servicecertsigner.config.openshift.io/v1alpha1
kind: APIServiceCABundleInjectorConfig
caBundleFile: /var/run/configmaps/signing-cabundle/ca-bundle.crt
`)

func v400ApiserviceCabundleControllerDefaultconfigYamlBytes() ([]byte, error) {
	return _v400ApiserviceCabundleControllerDefaultconfigYaml, nil
}

func v400ApiserviceCabundleControllerDefaultconfigYaml() (*asset, error) {
	bytes, err := v400ApiserviceCabundleControllerDefaultconfigYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/apiservice-cabundle-controller/defaultconfig.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400CabundleInjectionControllerClusterroleYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:controller:cabundle-injector
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resourceNames:
  - extension-apiserver-authentication
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
`)

func v400CabundleInjectionControllerClusterroleYamlBytes() ([]byte, error) {
	return _v400CabundleInjectionControllerClusterroleYaml, nil
}

func v400CabundleInjectionControllerClusterroleYaml() (*asset, error) {
	bytes, err := v400CabundleInjectionControllerClusterroleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/cabundle-injection-controller/clusterrole.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400CabundleInjectionControllerClusterrolebindingYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:controller:cabundle-injector
roleRef:
  kind: ClusterRole
  name: system:openshift:controller:cabundle-injector
subjects:
- kind: ServiceAccount
  namespace: openshift-service-ca
  name: cabundle-injector-sa
`)

func v400CabundleInjectionControllerClusterrolebindingYamlBytes() ([]byte, error) {
	return _v400CabundleInjectionControllerClusterrolebindingYaml, nil
}

func v400CabundleInjectionControllerClusterrolebindingYaml() (*asset, error) {
	bytes, err := v400CabundleInjectionControllerClusterrolebindingYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/cabundle-injection-controller/clusterrolebinding.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400CabundleInjectionControllerCmYaml = []byte(`apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-service-ca
  name: cabundle-injector-config
data:
  controller-config.yaml:
`)

func v400CabundleInjectionControllerCmYamlBytes() ([]byte, error) {
	return _v400CabundleInjectionControllerCmYaml, nil
}

func v400CabundleInjectionControllerCmYaml() (*asset, error) {
	bytes, err := v400CabundleInjectionControllerCmYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/cabundle-injection-controller/cm.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400CabundleInjectionControllerDefaultconfigYaml = []byte(`apiVersion: servicecertsigner.config.openshift.io/v1alpha1
kind: CABundleInjectorConfig
caBundleFile: /var/run/configmaps/signing-cabundle/ca-bundle.crt
`)

func v400CabundleInjectionControllerDefaultconfigYamlBytes() ([]byte, error) {
	return _v400CabundleInjectionControllerDefaultconfigYaml, nil
}

func v400CabundleInjectionControllerDefaultconfigYaml() (*asset, error) {
	bytes, err := v400CabundleInjectionControllerDefaultconfigYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/cabundle-injection-controller/defaultconfig.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400CabundleInjectionControllerDeploymentYaml = []byte(`apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-service-ca
  name: cabundle-injector
  labels:
    app: cabundle-injector
    cabundle-injector: "true"
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cabundle-injector
      cabundle-injector: "true"
  template:
    metadata:
      name: cabundle-injector
      labels:
        app: cabundle-injector
        cabundle-injector: "true"
    spec:
      serviceAccountName: cabundle-injector-sa
      containers:
      - name: cabundle-injector-controller
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["service-ca-operator", "cabundle-injector"]
        args:
        - "--config=/var/run/configmaps/config/controller-config.yaml"
        ports:
        - containerPort: 8443
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/configmaps/signing-cabundle
          name: signing-cabundle
      volumes:
      - name: signing-cabundle
        configMap:
          name: signing-cabundle
      - name: config
        configMap:
          name: cabundle-injector-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
`)

func v400CabundleInjectionControllerDeploymentYamlBytes() ([]byte, error) {
	return _v400CabundleInjectionControllerDeploymentYaml, nil
}

func v400CabundleInjectionControllerDeploymentYaml() (*asset, error) {
	bytes, err := v400CabundleInjectionControllerDeploymentYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/cabundle-injection-controller/deployment.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400CabundleInjectionControllerNsYaml = []byte(`apiVersion: v1
kind: Namespace
metadata:
  name: openshift-service-ca
  labels:
    openshift.io/run-level: "1"
  annotations:
    openshift.io/node-selector: ""
`)

func v400CabundleInjectionControllerNsYamlBytes() ([]byte, error) {
	return _v400CabundleInjectionControllerNsYaml, nil
}

func v400CabundleInjectionControllerNsYaml() (*asset, error) {
	bytes, err := v400CabundleInjectionControllerNsYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/cabundle-injection-controller/ns.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400CabundleInjectionControllerRoleYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:openshift:controller:cabundle-injector
  namespace: openshift-service-ca
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
`)

func v400CabundleInjectionControllerRoleYamlBytes() ([]byte, error) {
	return _v400CabundleInjectionControllerRoleYaml, nil
}

func v400CabundleInjectionControllerRoleYaml() (*asset, error) {
	bytes, err := v400CabundleInjectionControllerRoleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/cabundle-injection-controller/role.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400CabundleInjectionControllerRolebindingYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:controller:cabundle-injector
  namespace: openshift-service-ca
roleRef:
  kind: Role
  name: system:openshift:controller:cabundle-injector
subjects:
- kind: ServiceAccount
  namespace: openshift-service-ca
  name: cabundle-injector-sa
`)

func v400CabundleInjectionControllerRolebindingYamlBytes() ([]byte, error) {
	return _v400CabundleInjectionControllerRolebindingYaml, nil
}

func v400CabundleInjectionControllerRolebindingYaml() (*asset, error) {
	bytes, err := v400CabundleInjectionControllerRolebindingYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/cabundle-injection-controller/rolebinding.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400CabundleInjectionControllerSaYaml = []byte(`apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-service-ca
  name: cabundle-injector-sa
`)

func v400CabundleInjectionControllerSaYamlBytes() ([]byte, error) {
	return _v400CabundleInjectionControllerSaYaml, nil
}

func v400CabundleInjectionControllerSaYaml() (*asset, error) {
	bytes, err := v400CabundleInjectionControllerSaYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/cabundle-injection-controller/sa.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400CabundleInjectionControllerSigningCabundleYaml = []byte(`apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-service-ca
  name: signing-cabundle
data:
  ca-bundle.crt:
`)

func v400CabundleInjectionControllerSigningCabundleYamlBytes() ([]byte, error) {
	return _v400CabundleInjectionControllerSigningCabundleYaml, nil
}

func v400CabundleInjectionControllerSigningCabundleYaml() (*asset, error) {
	bytes, err := v400CabundleInjectionControllerSigningCabundleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/cabundle-injection-controller/signing-cabundle.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400ServiceServingCertSignerControllerClusterroleYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:controller:service-serving-cert-signer
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resourceNames:
  - extension-apiserver-authentication
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
`)

func v400ServiceServingCertSignerControllerClusterroleYamlBytes() ([]byte, error) {
	return _v400ServiceServingCertSignerControllerClusterroleYaml, nil
}

func v400ServiceServingCertSignerControllerClusterroleYaml() (*asset, error) {
	bytes, err := v400ServiceServingCertSignerControllerClusterroleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/service-serving-cert-signer-controller/clusterrole.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400ServiceServingCertSignerControllerClusterrolebindingYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:controller:service-serving-cert-signer
roleRef:
  kind: ClusterRole
  name: system:openshift:controller:service-serving-cert-signer
subjects:
- kind: ServiceAccount
  namespace: openshift-service-ca
  name: service-serving-cert-signer-sa
`)

func v400ServiceServingCertSignerControllerClusterrolebindingYamlBytes() ([]byte, error) {
	return _v400ServiceServingCertSignerControllerClusterrolebindingYaml, nil
}

func v400ServiceServingCertSignerControllerClusterrolebindingYaml() (*asset, error) {
	bytes, err := v400ServiceServingCertSignerControllerClusterrolebindingYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/service-serving-cert-signer-controller/clusterrolebinding.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400ServiceServingCertSignerControllerCmYaml = []byte(`apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-service-ca
  name: service-serving-cert-signer-config
data:
  controller-config.yaml:
`)

func v400ServiceServingCertSignerControllerCmYamlBytes() ([]byte, error) {
	return _v400ServiceServingCertSignerControllerCmYaml, nil
}

func v400ServiceServingCertSignerControllerCmYaml() (*asset, error) {
	bytes, err := v400ServiceServingCertSignerControllerCmYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/service-serving-cert-signer-controller/cm.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400ServiceServingCertSignerControllerDefaultconfigYaml = []byte(`apiVersion: servicecertsigner.config.openshift.io/v1alpha1
kind: ServiceServingCertSignerConfig
signer:
  certFile: /var/run/secrets/signing-key/tls.crt
  keyFile: /var/run/secrets/signing-key/tls.key
intermediateCertFile: /var/run/secrets/signing-key/intermediate-ca.crt
`)

func v400ServiceServingCertSignerControllerDefaultconfigYamlBytes() ([]byte, error) {
	return _v400ServiceServingCertSignerControllerDefaultconfigYaml, nil
}

func v400ServiceServingCertSignerControllerDefaultconfigYaml() (*asset, error) {
	bytes, err := v400ServiceServingCertSignerControllerDefaultconfigYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/service-serving-cert-signer-controller/defaultconfig.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400ServiceServingCertSignerControllerDeploymentYaml = []byte(`apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-service-ca
  name: service-serving-cert-signer
  labels:
    app: service-serving-cert-signer
    service-serving-cert-signer: "true"
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-serving-cert-signer
      service-serving-cert-signer: "true"
  template:
    metadata:
      name: service-serving-cert-signer
      labels:
        app: service-serving-cert-signer
        service-serving-cert-signer: "true"
    spec:
      serviceAccountName: service-serving-cert-signer-sa
      containers:
      - name: service-serving-cert-signer-controller
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["service-ca-operator", "serving-cert-signer"]
        args:
        - "--config=/var/run/configmaps/config/controller-config.yaml"
        ports:
        - containerPort: 8443
        resources:
          requests:
            memory: 120Mi
            cpu: 10m
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/signing-key
          name: signing-key
      volumes:
      - name: signing-key
        secret:
          secretName: signing-key
      - name: config
        configMap:
          name: service-serving-cert-signer-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
`)

func v400ServiceServingCertSignerControllerDeploymentYamlBytes() ([]byte, error) {
	return _v400ServiceServingCertSignerControllerDeploymentYaml, nil
}

func v400ServiceServingCertSignerControllerDeploymentYaml() (*asset, error) {
	bytes, err := v400ServiceServingCertSignerControllerDeploymentYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/service-serving-cert-signer-controller/deployment.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400ServiceServingCertSignerControllerNsYaml = []byte(`apiVersion: v1
kind: Namespace
metadata:
  name: openshift-service-ca
  labels:
    openshift.io/run-level: "1"
  annotations:
    openshift.io/node-selector: ""
`)

func v400ServiceServingCertSignerControllerNsYamlBytes() ([]byte, error) {
	return _v400ServiceServingCertSignerControllerNsYaml, nil
}

func v400ServiceServingCertSignerControllerNsYaml() (*asset, error) {
	bytes, err := v400ServiceServingCertSignerControllerNsYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/service-serving-cert-signer-controller/ns.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400ServiceServingCertSignerControllerRoleYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:openshift:controller:service-serving-cert-signer
  namespace: openshift-service-ca
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
`)

func v400ServiceServingCertSignerControllerRoleYamlBytes() ([]byte, error) {
	return _v400ServiceServingCertSignerControllerRoleYaml, nil
}

func v400ServiceServingCertSignerControllerRoleYaml() (*asset, error) {
	bytes, err := v400ServiceServingCertSignerControllerRoleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/service-serving-cert-signer-controller/role.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400ServiceServingCertSignerControllerRolebindingYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:controller:service-serving-cert-signer
  namespace: openshift-service-ca
roleRef:
  kind: Role
  name: system:openshift:controller:service-serving-cert-signer
subjects:
- kind: ServiceAccount
  namespace: openshift-service-ca
  name: service-serving-cert-signer-sa
`)

func v400ServiceServingCertSignerControllerRolebindingYamlBytes() ([]byte, error) {
	return _v400ServiceServingCertSignerControllerRolebindingYaml, nil
}

func v400ServiceServingCertSignerControllerRolebindingYaml() (*asset, error) {
	bytes, err := v400ServiceServingCertSignerControllerRolebindingYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/service-serving-cert-signer-controller/rolebinding.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400ServiceServingCertSignerControllerSaYaml = []byte(`apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-service-ca
  name: service-serving-cert-signer-sa
`)

func v400ServiceServingCertSignerControllerSaYamlBytes() ([]byte, error) {
	return _v400ServiceServingCertSignerControllerSaYaml, nil
}

func v400ServiceServingCertSignerControllerSaYaml() (*asset, error) {
	bytes, err := v400ServiceServingCertSignerControllerSaYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/service-serving-cert-signer-controller/sa.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v400ServiceServingCertSignerControllerSigningSecretYaml = []byte(`apiVersion: v1
kind: Secret
metadata:
  namespace: openshift-service-ca
  name: signing-key
type: kubernetes.io/tls
data:
  tls.crt:
  tls.key:
`)

func v400ServiceServingCertSignerControllerSigningSecretYamlBytes() ([]byte, error) {
	return _v400ServiceServingCertSignerControllerSigningSecretYaml, nil
}

func v400ServiceServingCertSignerControllerSigningSecretYaml() (*asset, error) {
	bytes, err := v400ServiceServingCertSignerControllerSigningSecretYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.0.0/service-serving-cert-signer-controller/signing-secret.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"v4.0.0/apiservice-cabundle-controller/defaultconfig.yaml":              v400ApiserviceCabundleControllerDefaultconfigYaml,
	"v4.0.0/cabundle-injection-controller/clusterrole.yaml":                 v400CabundleInjectionControllerClusterroleYaml,
	"v4.0.0/cabundle-injection-controller/clusterrolebinding.yaml":          v400CabundleInjectionControllerClusterrolebindingYaml,
	"v4.0.0/cabundle-injection-controller/cm.yaml":                          v400CabundleInjectionControllerCmYaml,
	"v4.0.0/cabundle-injection-controller/defaultconfig.yaml":               v400CabundleInjectionControllerDefaultconfigYaml,
	"v4.0.0/cabundle-injection-controller/deployment.yaml":                  v400CabundleInjectionControllerDeploymentYaml,
	"v4.0.0/cabundle-injection-controller/ns.yaml":                          v400CabundleInjectionControllerNsYaml,
	"v4.0.0/cabundle-injection-controller/role.yaml":                        v400CabundleInjectionControllerRoleYaml,
	"v4.0.0/cabundle-injection-controller/rolebinding.yaml":                 v400CabundleInjectionControllerRolebindingYaml,
	"v4.0.0/cabundle-injection-controller/sa.yaml":                          v400CabundleInjectionControllerSaYaml,
	"v4.0.0/cabundle-injection-controller/signing-cabundle.yaml":            v400CabundleInjectionControllerSigningCabundleYaml,
	"v4.0.0/service-serving-cert-signer-controller/clusterrole.yaml":        v400ServiceServingCertSignerControllerClusterroleYaml,
	"v4.0.0/service-serving-cert-signer-controller/clusterrolebinding.yaml": v400ServiceServingCertSignerControllerClusterrolebindingYaml,
	"v4.0.0/service-serving-cert-signer-controller/cm.yaml":                 v400ServiceServingCertSignerControllerCmYaml,
	"v4.0.0/service-serving-cert-signer-controller/defaultconfig.yaml":      v400ServiceServingCertSignerControllerDefaultconfigYaml,
	"v4.0.0/service-serving-cert-signer-controller/deployment.yaml":         v400ServiceServingCertSignerControllerDeploymentYaml,
	"v4.0.0/service-serving-cert-signer-controller/ns.yaml":                 v400ServiceServingCertSignerControllerNsYaml,
	"v4.0.0/service-serving-cert-signer-controller/role.yaml":               v400ServiceServingCertSignerControllerRoleYaml,
	"v4.0.0/service-serving-cert-signer-controller/rolebinding.yaml":        v400ServiceServingCertSignerControllerRolebindingYaml,
	"v4.0.0/service-serving-cert-signer-controller/sa.yaml":                 v400ServiceServingCertSignerControllerSaYaml,
	"v4.0.0/service-serving-cert-signer-controller/signing-secret.yaml":     v400ServiceServingCertSignerControllerSigningSecretYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"v4.0.0": {nil, map[string]*bintree{
		"apiservice-cabundle-controller": {nil, map[string]*bintree{
			"defaultconfig.yaml": {v400ApiserviceCabundleControllerDefaultconfigYaml, map[string]*bintree{}},
		}},
		"cabundle-injection-controller": {nil, map[string]*bintree{
			"clusterrole.yaml":        {v400CabundleInjectionControllerClusterroleYaml, map[string]*bintree{}},
			"clusterrolebinding.yaml": {v400CabundleInjectionControllerClusterrolebindingYaml, map[string]*bintree{}},
			"cm.yaml":                 {v400CabundleInjectionControllerCmYaml, map[string]*bintree{}},
			"defaultconfig.yaml":      {v400CabundleInjectionControllerDefaultconfigYaml, map[string]*bintree{}},
			"deployment.yaml":         {v400CabundleInjectionControllerDeploymentYaml, map[string]*bintree{}},
			"ns.yaml":                 {v400CabundleInjectionControllerNsYaml, map[string]*bintree{}},
			"role.yaml":               {v400CabundleInjectionControllerRoleYaml, map[string]*bintree{}},
			"rolebinding.yaml":        {v400CabundleInjectionControllerRolebindingYaml, map[string]*bintree{}},
			"sa.yaml":                 {v400CabundleInjectionControllerSaYaml, map[string]*bintree{}},
			"signing-cabundle.yaml":   {v400CabundleInjectionControllerSigningCabundleYaml, map[string]*bintree{}},
		}},
		"service-serving-cert-signer-controller": {nil, map[string]*bintree{
			"clusterrole.yaml":        {v400ServiceServingCertSignerControllerClusterroleYaml, map[string]*bintree{}},
			"clusterrolebinding.yaml": {v400ServiceServingCertSignerControllerClusterrolebindingYaml, map[string]*bintree{}},
			"cm.yaml":                 {v400ServiceServingCertSignerControllerCmYaml, map[string]*bintree{}},
			"defaultconfig.yaml":      {v400ServiceServingCertSignerControllerDefaultconfigYaml, map[string]*bintree{}},
			"deployment.yaml":         {v400ServiceServingCertSignerControllerDeploymentYaml, map[string]*bintree{}},
			"ns.yaml":                 {v400ServiceServingCertSignerControllerNsYaml, map[string]*bintree{}},
			"role.yaml":               {v400ServiceServingCertSignerControllerRoleYaml, map[string]*bintree{}},
			"rolebinding.yaml":        {v400ServiceServingCertSignerControllerRolebindingYaml, map[string]*bintree{}},
			"sa.yaml":                 {v400ServiceServingCertSignerControllerSaYaml, map[string]*bintree{}},
			"signing-secret.yaml":     {v400ServiceServingCertSignerControllerSigningSecretYaml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
